spring.application.name=accountmanagement


amazon.aws.endpoint=http://localhost:8009  # Use real AWS endpoint if in prod
amazon.aws.region=ap-south-1
amazon.aws.accesskey=awivqm
amazon.aws.secretkey=6mapgqm
