amazon.aws.accessKey=u6ui4
amazon.aws.secretKey=koai5m
amazon.dynamodb.endpoint=http://localhost:8000
amazon.aws.region=ap-south-1
server.port=8070
spring.main.allow-bean-definition-overriding=true
# application.properties
logging.level.org.springframework.web=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajappansellamuthu@gmail.com
spring.mail.password=mdvsizlimlricybr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
