package com.yaazhtech.accountmanagement.data;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.data.annotation.Id;




@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor  // Default constructor is required by AWS DynamoDB SDK
@DynamoDBTable(tableName = "pupilAccount")
public class PupilAccount  {

    @Id
    private PupilPrimaryKey key;

    @DynamoDBAttribute(attributeName = "id")
    private String id;
    @DynamoDBAttribute(attributeName = "password")
    private String password;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "userName")
    private String userName;






    @DynamoDBRangeKey(attributeName = "createdAt")
    @DynamoDBAttribute(attributeName = "createdAt")
    public String getCreatedAt() {
        return key.getCreatedAt();
    }

    public void setCreatedAt(String createdAt) {
        if (key == null) {
            key = new PupilPrimaryKey();
        }
        key.setCreatedAt(createdAt);
    }


    @DynamoDBHashKey(attributeName = "category")
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "category")
    public String getCategory() {
        return key.getCategory();
    }

    public void setCategory(String orgName) {
        if (key == null) {
            key = new PupilPrimaryKey();
        }
        key.setCategory(orgName);
    }

    @DynamoDBIndexHashKey(attributeName = "pupilEmail", globalSecondaryIndexName = "pupilEmail")
    @DynamoDBAttribute(attributeName = "pupilEmail")
    public String getPupilEmail() {
        return key.getPupilEmail();
    }

    public void setPupilEmail(String pupilEmail) {
        if (key == null) {
            key = new PupilPrimaryKey();
        }
        key.setPupilEmail(pupilEmail);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}



