package com.yaazhtech.accountmanagement.data;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.data.annotation.Id;




@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor  // Default constructor is required by AWS DynamoDB SDK
@DynamoDBTable(tableName = "pupilAccount")
public class PupilAccount  {

    @Id
    private PupilPrimaryKey key;

    @DynamoDBAttribute(attributeName = "id")
    private String id;
    @DynamoDBAttribute(attributeName = "password")
    private String password;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "email")
    private String email;
    @DynamoDBAttribute(attributeName = "userName")
    private String userName;
    @DynamoDBAttribute(attributeName = "phone")
    private String phone;
    @DynamoDBAttribute(attributeName = "role")
    private String role;
    @DynamoDBAttribute(attributeName = "otpData")
    private String otpData;
    @DynamoDBAttribute(attributeName = "active")
    private boolean active;







    @DynamoDBRangeKey(attributeName = "createdAt")
    @DynamoDBAttribute(attributeName = "createdAt")
    public String getCreatedAt() {
        return key.getCreatedAt();
    }

    public void setCreatedAt(String createdAt) {
        if (key == null) {
            key = new PupilPrimaryKey();
        }
        key.setCreatedAt(createdAt);
    }


    @DynamoDBHashKey(attributeName = "category")
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "category")
    public String getCategory() {
        return key.getCategory();
    }

    public void setCategory(String orgName) {
        if (key == null) {
            key = new PupilPrimaryKey();
        }
        key.setCategory(orgName);
    }

    @DynamoDBIndexHashKey(attributeName = "pupilEmail", globalSecondaryIndexName = "pupilEmail")
    @DynamoDBAttribute(attributeName = "pupilEmail")
    public String getPupilEmail() {
        return key.getPupilEmail();
    }

    public void setPupilEmail(String pupilEmail) {
        if (key == null) {
            key = new PupilPrimaryKey();
        }
        key.setPupilEmail(pupilEmail);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNo() {
        return phone;
    }

    public void setPhoneNo(String phoneNo) {
        this.phone = phoneNo;
    }


    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getOtpData() {
        return otpData;
    }

    public void setOtpData(String otpData) {
        this.otpData = otpData;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }



    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
}



